config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :simulations
  resources :universes
  resources :physics_bodies

  # Defines the root path route ("/")
  root 'simulations#index'
end

app/models/simulation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: simulations
#
#  id               :uuid             not null, primary key
#  computation_time :decimal(, )
#  computed_at      :datetime
#  name             :text             not null
#  slug             :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_simulations_on_name  (name) UNIQUE
#  index_simulations_on_slug  (slug) UNIQUE
#
class Simulation < ApplicationRecord
  has_rich_text :description
  has_one :universe, inverse_of: :simulation, dependent: :destroy
  has_many :physics_bodies, dependent: :destroy

  accepts_nested_attributes_for :universe
  accepts_nested_attributes_for :physics_bodies, allow_destroy: true, reject_if: proc { |attr| attr['name'].blank? }

  validates :name, presence: true
  validates :name, uniqueness: true

  extend FriendlyId
  friendly_id :name, use: :history

  def should_generate_new_friendly_id?
    slug.blank? or name_changed?
  end

  def computed?
    not self.computed_at.nil? and not self.computation_time.nil?
  end
end

app/controllers/simulations_controller.rb
# frozen_string_literal: true

# Defines all actions available to simulations through HTTP requests.
class SimulationsController < ApplicationController
  before_action :set_simulation, only: [:show, :edit, :update, :destroy]

  # GET /simulations or /simulations.json
  def index
    @simulations = Simulation.all
  end

  # GET /simulations/1 or /simulations/1.json
  def show
    # Pass the simulation data needed for rendering to the Javascript in the view.
    gon.physics_bodies = []
    @simulation.physics_bodies.each do |physics_body|
      # Scale down the values to prevent float overflow in ThreeJS rendering.
      scaled_position_x = physics_body.initial_position_x * Universe::RENDER_SCALE
      scaled_position_y = physics_body.initial_position_y * Universe::RENDER_SCALE
      scaled_position_z = physics_body.initial_position_z * Universe::RENDER_SCALE
      scaled_radius = physics_body.radius * Universe::RENDER_SCALE

      gon.physics_bodies << { name: physics_body.name,
                              x: scaled_position_x,
                              y: scaled_position_y,
                              z: scaled_position_z,
                              radius: scaled_radius }
    end

    # Redirect to the latest URL if an old slug was used.
    redirect_to @simulation, status: :moved_permanently unless request.path == simulation_path(@simulation)
  end

  # GET /simulations/new
  def new
    @simulation = Simulation.new
    @simulation.build_universe
  end

  # GET /simulations/1/edit
  def edit; end

  # POST /simulations or /simulations.json
  def create
    @simulation = Simulation.new(simulation_params)

    respond_to do |format|
      if @simulation.save
        format.html { redirect_to simulation_url(@simulation), notice: 'Simulation was successfully created.' }
        format.json { render :show, status: :created, location: @simulation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simulations/1 or /simulations/1.json
  def update
    respond_to do |format|
      if @simulation.update(simulation_params)
        format.html { redirect_to simulation_url(@simulation), notice: 'Simulation was successfully updated.' }
        format.json { render :show, status: :ok, location: @simulation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simulations/1 or /simulations/1.json
  def destroy
    @simulation.destroy

    respond_to do |format|
      format.html { redirect_to simulations_url, notice: 'Simulation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_simulation
    @simulation = Simulation.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Render the 404 page if a slug was used that doesn't match any records.
    render file: "#{Rails.root}/public/404.html", status: :not_found and return
  end

  # Only allow a list of trusted parameters through.
  def simulation_params
    params.require(:simulation).permit(:name, :description, universe_attributes: [
                                         :id, :start_time, :end_time, :timestep, :number_of_timesteps
                                       ], physics_bodies_attributes: [
                                         :_destroy, :id, :name, :description, :initial_mass, :radius,
                                         :initial_position_x, :initial_position_y, :initial_position_z,
                                         :initial_velocity_x, :initial_velocity_y, :initial_velocity_z
                                       ])
  end
end

app/helpers/simulations_helper.rb
# frozen_string_literal: true

require 'benchmark'

# Defines helper methods specific to simulations.
module SimulationsHelper
  def solve(simulation)
    simulation.computed_at = Time.zone.now

    computation_time = Benchmark.realtime do
      solve_with_benchmarking(simulation)
    end

    simulation.computation_time = computation_time
    simulation.save!
  end

  private

  def solve_with_benchmarking(simulation)
    write_initial_conditions(simulation)
    call_python_solver(simulation)
    read_final_results(simulation)
  end

  def write_initial_conditions(simulation); end

  def call_python_solver(simulation); end

  def read_final_results(simulation); end
end

app/views/simulations/_form.html.erb
<%= form_with(model: simulation, class: "contents") do |form| %>
  <% if simulation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(simulation.errors.count, "error") %> prohibited this simulation from being saved:</h2>

      <ul>
        <% simulation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_area :name, rows: 2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <h2 class="font-bold text-2xl">Times</h2>
  <%= form.fields_for :universe do |universe_form| %>
    <h3 class="text-lg">Only 3 out of 4 time fields are required, the missing value will be automatically calculated.</h3>
    <div class="my-5">
      <%= universe_form.label :start_time, 'Start Time (seconds)' %>
      <%= universe_form.text_field :start_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= universe_form.label :end_time, 'End Time (seconds)' %>
      <%= universe_form.text_field :end_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= universe_form.label :timestep, 'Timestep (seconds)' %>
      <%= universe_form.text_field :timestep, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= universe_form.label :number_of_timesteps, 'Number of Timesteps' %>
      <%= universe_form.number_field :number_of_timesteps, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  <% end %>

  <h2 class="font-bold text-2xl">Physics Bodies</h2>
  <div data-controller="nested-form">
    <template data-target='nested-form.template'>
      <%= form.fields_for :physics_bodies, PhysicsBody.new, child_index: 'TEMPLATE_RECORD' do |physics_body| %>
        <%= render 'physics_bodies/nested_form_fields', form: physics_body %>
      <% end %>
    </template>

    <%= form.fields_for :physics_bodies do |physics_body| %>
      <%= render 'physics_bodies/nested_form_fields', form: physics_body %>
    <% end %>

    <div data-target="nested-form.add_item">
      <%= link_to "Add Physics Body", "#", data: { action: "nested-form#add_association" }, class: 'ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium' %>
    </div>
  </div>
  <br>
  <hr>
  <br>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/simulations/_simulation.html.erb
<div id="<%= dom_id simulation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= simulation.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= simulation.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Computation time:</strong>
    <%= simulation.computation_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Computed at:</strong>
    <%= simulation.computed_at %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this simulation", simulation, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this simulation', edit_simulation_path(simulation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/simulations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing simulation</h1>

  <%= render "form", simulation: @simulation %>

  <%= link_to "Show this simulation", @simulation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to simulations", simulations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/simulations/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Simulations</h1>
    <%= link_to 'New simulation', new_simulation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="simulations" class="min-w-full">
    <%= render @simulations %>
  </div>
</div>

app/views/simulations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Simulation</h1>

  <%= render "form", simulation: @simulation %>

  <%= link_to 'Back', :back, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/simulations/show.html.erb
<div>
  <div class="mx-auto md:w-2/3 w-full flex">
    <div class="mx-auto">
      <h1 class="text-4xl font-semibold"><%= @simulation.name %></h1>

      <%= @simulation.description %>

      <table class="w-full table-auto border border-slate-300 my-2">
        <thead>
          <tr>
            <th class="w-1/3 border border-slate-300">
              Physics Bodies Count
            </th>
            <th class="w-1/3 border border-slate-300">
              Computed On
            </th>
            <th class="w-1/3 border border-slate-300">
              Computation Time (seconds)
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="border border-slate-300">
              <%= @simulation.physics_bodies.size %>
            </td>
            <td class="border border-slate-300">
              <%= @simulation.computed_at.nil? ? 'Not Computed Yet' : @simulation.computed_at %>
            </td>
            <td class="border border-slate-300">
              <%= @simulation.computation_time.nil? ? '-' : @simulation.computation_time %>
            </td>
          </tr>
        </tbody>
      </table>

      <%= link_to 'Edit', edit_simulation_path(@simulation), class: "mt-2 rounded-lg py-2 px-5 bg-blue-600 inline-block text-white font-semibold" %>
      <div class="inline-block ml-2">
        <%= button_to 'Delete', simulation_path(@simulation), method: :delete, class: "mt-2 rounded-lg py-2 px-5 bg-red-600 text-white font-semibold" %>
      </div>
      <%= link_to 'Back', :back, class: "ml-2 rounded-lg py-2 px-5 bg-gray-100 inline-block font-medium" %>

      <div class="border border-2 border-slate-300 rounded-lg p-2 mt-4">
        <h3 class="text-2xl pb-2">Select a Background Image:</h3>
        <%= form_with class: 'p-2' do |form| %>
          <%= form.radio_button :background_image, 'constellation_figures', checked: true  %>
          <%= form.label :background_image_constellation_figures, 'Constellations' %>
          <%= form.radio_button :background_image, 'constellation_bounds' %>
          <%= form.label :background_image_constellation_bounds, 'Constellation Boundaries' %>
          <%= form.radio_button :background_image, 'celestial_grid'%>
          <%= form.label :background_image_celestial_grid, 'Celestial Grid' %>
          <%= form.radio_button :background_image, 'milkyway'%>
          <%= form.label :background_image_milkyway, 'Milkyway (Brightest Stars)' %>
        <% end %>

        <h3 class="text-2xl pb-2">Select Axes:</h3>
        <%= form_with class: 'p-2' do |form| %>
          <%= form.radio_button :axes, 'off', checked: true  %>
          <%= form.label :axes_off, 'Off' %>
          <%= form.radio_button :axes, 'on' %>
          <%= form.label :axes_on, 'On' %>
        <% end %>
      </div>

      <ul class="list-disc mx-6 my-2">
        <li><%= link_to 'About the Background Images', 'https://svs.gsfc.nasa.gov/4851', target: :_blank, class: 'text-blue-600 underline p-4' %></li>
        <li><%= link_to 'Source of Solar System 3D Models', 'https://solarsystem.nasa.gov/resources/', target: :_blank, class: 'text-blue-600 underline p-4' %></li>
      </ul>
    </div>
  </div>

  <% if @simulation.computed? %>
    <canvas id="simulation_canvas" class="m-2 h-96 max-h-screen"></canvas>
  <% else %>
    <h3 class="text-2xl">Simulation not run yet. Once its been computed the visualization will appear here.</h3>
  <% end %>
</div>